version: 2
updates:
  # Maven Dependencies (pom.xml)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maven Wrapper (mvnw)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    # Aktiviert Wrapper-Updates
    groups:
      maven-wrapper:
        patterns:
          - "org.apache.maven.wrapper:*"
